version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: ecton-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecton
      - POSTGRES_USER=ecton_user
      - POSTGRES_PASSWORD=ecton_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ecton-network

  # Meilisearch service
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: ecton-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=your-secret-master-key-here
      - MEILI_ENV=production
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    networks:
      - ecton-network

  # Next.js application
  ecton-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecton-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MEILISEARCH_URL=http://meilisearch:7700
      - NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY=your-secret-master-key-here
      - DATABASE_URL=postgresql://ecton_user:ecton_password@postgres:5432/ecton
    depends_on:
      - postgres
      - meilisearch
    restart: unless-stopped
    networks:
      - ecton-network

volumes:
  postgres_data:
  meilisearch_data:

networks:
  ecton-network:
    driver: bridge 